### PR TITLE
Added info.md

### PR DESCRIPTION
**Pull request by neha3001-singh**
Issue: 4

Commands that you used to complete this issue.

-git clone https://github.com/neha3001-singh/GoGit.git
-cd GoGit/CONTRIBUTORS/IIITA/Second_year
-mkdir "Neha Singh"
-touch info.md
-git add .
-git commit -m "Added info.md"
-git push

##Screenshot
image

### CODE REVIEW

**Comment by Elemento24** [comment]
Format of commit message is wrong!

**Comment by ABHAY0O7** [comment]
@neha3001-singh according to your first command, you cloned the wrong repo.

**Comment by neha3001-singh** [comment]
correction done!

**Comment by ABHAY0O7** [comment]
Thanks for your contribution @neha3001-singh

**Pull request merged**
