### PR TITLE
Added info.md

### PR DESCRIPTION
**Pull request by Sneh16Shah**
Issue: 4

Commands that you used to complete this issue.
-git clone https://github.com/Sneh16Shah/GoGit.git
-cd GoGit/CONTRIBUTORS/IIITA/Second_year
-git add .
-git commit -m "Added info.md"
-git push

##Screenshot
image

### CODE REVIEW

**Comment by Elemento24** [comment]
@Sneh16Shah You have not completed the 2nd task mentioned in the issue, and wrong commit message as well!

**Comment by ABHAY0O7** [comment]
@Sneh16Shah you cloned the wring repo.

**Comment by Sneh16Shah** [comment]
> @Sneh16Shah you cloned the wrong repo according to your first command.

Pls check again it is correct

**Comment by ABHAY0O7** [comment]
@Sneh16Shah Your commit message is wrong, doesn't match with the original one.

**Comment by Sneh16Shah** [comment]
> @Sneh16Shah Your commit message is wrong, doesn't match with the original one.

That's y I have made another commit

**Comment by ABHAY0O7** [comment]
Ok @Sneh16Shah , thanks for your contribution. 😄

**Pull request merged**
