### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by codesanta142**
Issue: 4

List out all the commands that you used to complete this task from the very beginning.

- git clone https://github.com/opencodeiiita/GoGit.git
- git add info.md
- git commit -m "add files"
- git push origin main

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @codesanta142 
Please update your PR message with the latest PR template.
Also, visit the GoGit channel of discord.

**Comment by codesanta142** [comment]
@ABHAY0O7 now plz verify

**Comment by ABHAY0O7** [comment]
Ok @codesanta142, You have completed the task correctly.
Notice that I have updated your PR message, please try to follow the similar from next time.
Also, try to follow the commit template, it will be helpful to you guys in the future. 

Thanks for your contribution.

**Comment by codesanta142** [comment]
> Ok @codesanta142, You have completed the task correctly. Notice that I have updated your PR message, please try to follow the similar from next time. Also, try to follow the commit template, it will be helpful to you guys in the future.
> 
> Thanks for your contribution.

Thanks @ABHAY0O7 , will surely follow it

**Pull request merged**
