### PR TITLE
Create a branch

### PR DESCRIPTION
**Pull request by Ksathwik03**
Issue: 8 

Commands that you used to complete this issue.
- git log --reverse
- git checkout c29e8fd225fa4a4ec1ae9df3a0630ea0cc7d0562
- git switch -c initial-branch
- git add .
- git commit -m "Create a branch"
- git push --set-upstream origin initial-branch

### CODE REVIEW

**Comment by Ksathwik03** [comment]
My bad changed it.

**Comment by ABHAY0O7** [comment]
No need to write '#' before issue number.

**Comment by Ksathwik03** [comment]
> No need to write '#' before issue number.

Wrote it 😅.

**Comment by ABHAY0O7** [comment]
> > No need to write '#' before issue number.
> 
> Wrote it 😅.

Then remove it.

**Comment by Ksathwik03** [comment]
> > > No need to write '#' before issue number.
> > 
> > 
> > Wrote it 😅.
> 
> Then remove it.

Done 👍🏻

**Comment by ABHAY0O7** [comment]
Hey @Ksathwik03, your answer is half correct.

See this thing is correct that if you initialize your repo using `git init` then this will create a master branch as default. This is the correct half-answer to my question.
image

But after that, you write about how to change your default branch from master to main or vice-versa. But the task's question was not this, see here
image

I asked you that in which case Git/GitHub creates the main branch as default (without changing the master to main). This part has also a similar answer as that of the first part. So, do some more research and try some things practically on your own. 
You will definitely get the answer. 😄 
You have still plenty of time to complete this task.

ATB. 👍🏽

**Comment by Ksathwik03** [comment]
> Hey @Ksathwik03, your answer is half correct.
> 
> See this thing is correct that if you initialize your repo using `git init` then this will create a master branch as default. This is the correct half-answer to my question. image
> 
> But after that, you write about how to change your default branch from master to main or vice-versa. But the task's question was not this, see here image
> 
> I asked you that in which case Git/GitHub creates the main branch as default (without changing the master to main). This part has also a similar answer as that of the first part. So, do some more research and try some things practically on your own. You will definitely get the answer. 😄 You have still plenty of time to complete this task.
> 
> ATB. 👍🏽

Sure i will make the required changes 🙂.

**Comment by ABHAY0O7** [comment]
Okay @Ksathwik03, your answer is correct.
Please also paste the question above your answer.
Read the third point of contributing.md.

**Comment by Ksathwik03** [comment]
@ABHAY0O7 done 🥳

**Comment by ABHAY0O7** [comment]
LGTM, @Ksathwik03 
You successfully completed this task. 🥳

**Pull request merged**
