### PR TITLE
Added AmanVerma and info.md

### PR DESCRIPTION
**Pull request by Aman-IIITA**
Issue: 4
- git clone https://github.com/Aman-IIITA/GoGit.git
- mkdir AmanVerma
- cd AmanVerma
- touch info.md
- git add .
- git commit -m "Added AmanVerma and info.md"
- git push

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @Aman-IIITA 
Please update your PR message with the latest PR template.
Also, visit the GoGit channel of discord.

**Comment by Aman-IIITA** [comment]
@ABHAY0O7  sir Can you please check if have completed the Issue 4 properly

**Comment by Aman-IIITA** [comment]
Issue: 6 
Deleted the listed files.

**Comment by ABHAY0O7** [comment]
Hey @Aman-IIITA, 
I think you have to do issue #4 only, but it seems that you make this PR for issue #6.
Do only what I told you to do in issue #4, because only that issue is open for everyone.

**Comment by ABHAY0O7** [comment]
@Aman-IIITA 
You only have to do the task in issue 4, don't do anything else.
Please restore the deleted files or redo the task with a new PR.

**Comment by Aman-IIITA** [comment]
Hope I have done correct this time.

**Comment by ABHAY0O7** [comment]
LGTM
Thanks for your contribution @Aman-IIITA

**Pull request merged**
