### PR TITLE
Added Info.md

### PR DESCRIPTION
**Pull request by srishtayy**
Issue: 4

Commands that you used to complete this issue.

-git clone https://github.com/srishtayy/GoGit.git
-git add .
-git commit -m"Added info.md"
-git push origin

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @srishtayy 
If you didn't register for the open code then you can't contribute to its projects.
But if you registered, then contact the admins on the discord server and report this issue.

**Comment by garvitchittora** [comment]
@ABHAY0O7 merge, everything is correct. It will automatically add an entry in DB.

**Comment by srishtayy** [comment]
Sir,please verify

**Comment by ABHAY0O7** [comment]
Hey @srishtayy, please don't do unnecessary changes.
You don't need to change the content of `CONTRIBUTING.md` please remove those changes.
Also, your `info.md` is in the wrong directory. Please read the CONTRIBUTING.md again.

**Comment by ABHAY0O7** [comment]
Thanks for your contribution @srishtayy  😄

**Pull request merged**
