### PR TITLE
Added info.md file

### PR DESCRIPTION
**Pull request by Siddharth1002**
Issue: 4

Commands that you used to complete this issue.

- git clone https://github.com/Siddharth1002/GoGit.git
- Created info.md file
- git add .
- git commit -m "Added info.md file"
- git push

### CODE REVIEW

**Comment by Mitul16** [comment]
@Siddharth1002 You have added your `info.md` in the wrong path. Correct its location.

And for this task #4, commit https://github.com/opencodeiiita/GoGit/pull/69/commits/cc7a484aa67b74ba6e9231926af3ade019a6707d looks incorrect.
Please go through the task.

**Comment by ABHAY0O7** [comment]
@Siddharth1002 
Please do the changes suggested by @Mitul16 
You only have time up to 11:59 pm today.

**Comment by Siddharth1002** [comment]
> @Siddharth1002 Please do the changes suggested by @Mitul16 You only have time up to 11:59 pm today.

@Mitul16 Made the necessary changes

**Comment by ABHAY0O7** [comment]
Hey @Siddharth1002 
You provided us the wrong repo link in your info.md.
But it seems that you already have made lots of repos on your own that's why I am merging this PR, from next time please read the task carefully.

Thanks for your contribution. 👍🏽

**Comment by Siddharth1002** [comment]
> Hey @Siddharth1002 You provided us the wrong repo link in your info.md. But it seems that you already have made lots of repos on your own that's why I am merging this PR, from next time please read the task carefully.
> 
> Thanks for your contribution. 👍🏽

Thank you as well. Didn't notice that i gave the wrong repo link. Sorry abt that!

**Pull request merged**
