### PR TITLE
added my info

### PR DESCRIPTION
**Pull request by Tanushree-coder**
Issue: 4

List out all the commands that you used to complete this task from the very beginning.

- git clone https://github.com/Tanushree-coder/GoGit.git
- git add info.md
- git commit -m "add files"
- git push origin main

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @Tanushree-coder 
You didn't provide the repo link.
Read the task again.

**Comment by ABHAY0O7** [comment]
Hey @Tanushree-coder 
Your first git command is wrong.

**Comment by Tanushree-coder** [comment]
> Hey @Tanushree-coder Your first git command is wrong.

corrected...please check now!

**Comment by ABHAY0O7** [comment]
Hey @Tanushree-coder 
It is clear that you copied the PR message from other PRs as none of your commit messages matches the command you provided in the PR message.
So, this is a warning to you.

I am closing this PR, please redo the task from the very beginning and make a PR.
Don't try to copy things. 👍🏽

**Pull request closed without merging**
