### PR TITLE
added and updated info.md

### PR DESCRIPTION
**Pull request by bipulkmr-crypto**
## Title
    Added info.md

## Description - 

    Issue: 4
List out all the commands that you used to complete this task from very beginning.
- git clone https://github.com/opencodeiiita/GoGit.git
- git add .
- git commit "Added and updated info.md"
- git push

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @bipulkmr-crypto 
Please update your PR message with the latest PR template.
Also, visit the GoGit channel of discord.

**Comment by bipulkmr-crypto** [comment]
> Hey @bipulkmr-crypto Please update your PR message with the latest PR template. Also, visit the GoGit channel of discord.

Have updated the template please go through

**Comment by ABHAY0O7** [comment]
Hey @bipulkmr-crypto, 
According to your first command, it seems that you cloned the wrong repo.
Please correct it.

**Comment by bipulkmr-crypto** [comment]
> Hey @bipulkmr-crypto, According to your first command, it seems that you cloned the wrong repo. Please correct it.

Hey corrected the PR message please review it.

**Comment by ABHAY0O7** [comment]
Your third command is still wrong.

**Comment by bipulkmr-crypto** [comment]
> Your third command is still wrong 
Please review now.

**Comment by ABHAY0O7** [comment]
Hey @bipulkmr-crypto  You added your `info.md` file in the wrong directory.
Please read the `CONTRIBUTING.md` again and then update the PR.

**Comment by ABHAY0O7** [comment]
Please correct all the things @bipulkmr-crypto 
You have only 5 more minutes.

**Pull request closed without merging**
