### PR TITLE
updated info.md file

### PR DESCRIPTION
**Pull request by james3gh**
Issue: 4

Commands that you used to complete this issue.
- git clone https://github.com/james3gh/GoGit

(Deleted the previous branch called info-file-feature)
- git add .
- git commit -m "updated info file"
- git push origin main

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @james3gh 
You made 2 PRs, please clarify which one I have to review?
And please close the other one. 🙏🏽

**Comment by james3gh** [comment]
This is the updated PR link https://github.com/opencodeiiita/GoGit/pull/52

Closed the previous PR

**Comment by ABHAY0O7** [comment]
Hey @james3gh 
If you are from IIT BHU, then why did you make your info.md inside IIITA?
Please read the CONTRIBUTING.md again.

**Comment by james3gh** [comment]
ohhh... I thought it will be for all the contributors.
 I will make a separate PR in new folder.

**Pull request closed without merging**
