### PR TITLE
Added info.md file

### PR DESCRIPTION
**Pull request by naman-cr**
Issue: 4 

Commands that you used to complete this issue.

-git clone https://github.com/naman-cr/GoGit
-cd Go-Git/CONTRIBUTORS/IIITA/Second_year
-mkdir NamanShukla
-touch info.md
-git add .
-git commit -m "Added info.md file"
-git push

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @naman-cr 
Your commit message differs from your original commit message.
Please correct it.

**Comment by ABHAY0O7** [comment]
@naman-cr 
please correct it before 11:59 today, otherwise, I will close this PR.

**Comment by naman-cr** [comment]
> @naman-cr please correct it before 11:59 today, otherwise, I will close this PR.

Updated

**Comment by ABHAY0O7** [comment]
Thanks for your contribution @naman-cr 👍🏽

**Pull request merged**
