### PR TITLE
Added info

### PR DESCRIPTION
**Pull request by Kajal-7**
Issue: 4 

Commands that you used to complete this issue.

$git clone https://github.com/opencodeiiita/GoGit.git
$git add .
$git comit -m "Added info"
$git push origin main

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @Kajal-7 
Some of your git commands are missing and some are wrong.
Please correct them.

**Comment by Kajal-7** [comment]
@ABHAY0O7 updated the comment!

**Comment by Kajal-7** [comment]
@ABHAY0O7 updated the commands.

**Comment by ABHAY0O7** [comment]
@Kajal-7 
None of your commit messages matches with the commit message you provided in the PR.
It means you copied the PR message from other PRs.
This is a warning to you.
I am closing this PR, please redo the task and make a PR.

**Comment by Kajal-7** [comment]
I had made commit twice. So twi messages have been there. First time link
was wrong in info. So i updated it committed changes again. I had done this
myself.

**Comment by Kajal-7** [comment]
Sir, I am new to github that's why I am facing issues. I will do the task
again.
Regards

**Pull request closed without merging**
