### PR TITLE
Done 1st Issue

### PR DESCRIPTION
**Pull request by codelord09**
Issue: 4 

Commands that you used to complete this issue.

-git clone https://github.com/codelord09/GoGit.git
-git add -A
-git commit -m "done 1st issue"
-git pull https://github.com/opencodeiiita/GoGit.git
-git push origin main

### CODE REVIEW

**Comment by codelord09** [comment]
@ABHAY0O7  can you please tell where I'm wrong.

**Comment by ABHAY0O7** [comment]
Hey @codelord09 
Your first git command has some errors, please correct them.

**Comment by codelord09** [comment]
Hey @ABHAY0O7, 
Check now please.

**Comment by ABHAY0O7** [comment]
Hey @codelord09 
your third command is wrong. Correct it.

**Comment by codelord09** [comment]
Hey @ABHAY0O7,
Is it okay now

**Comment by ABHAY0O7** [comment]
Okay @codelord09 
Everything is fine now.
Sorry for the inconvenience. 😓

**Pull request merged**
