### PR TITLE
For issue 6

### PR DESCRIPTION
**Pull request by Aneesh02**
Issue: 6

Commands that you used to complete this issue.

- git fetch
- git switch delete
- git add *
- git commit -m "Commit message - 46"
- git push origin delete

### CODE REVIEW

**Comment by Aneesh02** [comment]
@ABHAY0O7 For issue 6

**Comment by ABHAY0O7** [comment]
@Aneesh02 also write the git commands that you used after commit - 46.
Please write them in your next reply.

**Comment by Aneesh02** [comment]
@ABHAY0O7 

- git status
- git add *
- git commit -m "Commit message - 47"
- git push origin delete

**Comment by ABHAY0O7** [comment]
Ok, thanks for your contribution @Aneesh02

**Pull request merged**
