### PR TITLE
Added info for Ritwik in contributors

### PR DESCRIPTION
**Pull request by kaneki-ken260**
Issue: 4

Various commands used for this issue were :

- git clone https://github.com/kaneki-ken260/GoGit.git
- git status
- git add .
- git commit -m  "Added info for Ritwik in contributors"
- git push origin main

### CODE REVIEW

**Comment by Mitul16** [comment]
@kaneki-ken260 Your commands are incomplete.
Please specify only the `git` commands along with the proper *URL* and *branch name*

**Comment by kaneki-ken260** [comment]
Is it fine now?
The url of github repository and my github page is alright.

**Comment by Mitul16** [comment]
> Is it fine now? The url of github repository and my github page is alright.
> 
> @Mitul16

You need to provide the command using which you **cloned** the repository on your local system
```bash
git clone <URL>
```

**commit message** is missing, your commit command should have been invalid.
```bash
git commit -m <MESSAGE>
```

Other commands are correct :smile:

**Comment by kaneki-ken260** [comment]
I think this shall work now 😂.

**Comment by kaneki-ken260** [comment]
Done!!

**Pull request merged**
