### PR TITLE
Added info.md about Naman issue #4

### PR DESCRIPTION
**Pull request by Naman-11**
Issue : Issue number. #4 

Commands that I used to complete this issue.

- forked the repo
- git clone https://github.com/Naman-11/GoGit.git
- git add .
- git commit -m "Added info.md"
- git push
-
-

### CODE REVIEW

**Comment by Naman-11** [comment]
> Hey @Naman-11
> 
> PR template is not followed.
> 
> Thanks for contributing to OpenCode ✨✨!

Updated pr format

**Comment by ABHAY0O7** [comment]
Hey @Naman-11,
You have done most of the work wrong.
Please, again read the issue, and `CONTRIBUTING.md`.
Try to follow the latest PR template.
Visit the GoGit channel on discord and read the last pinned message.

**Comment by ABHAY0O7** [comment]
You write the commands in the wrong way.
You have to write correct and complete commands in the exact same order in which you used them.
And you can write only one command in a single line.
image

This is completely wrong.

**Comment by Naman-11** [comment]
> You write the commands in the wrong way. You have to write correct and complete commands in the exact same order in which you used them. And you can write only one command in a single line. image
> 
> This is completely wrong. Also, you pushed some other files which are not related to this task. Please delete them too. image

Should i just close this pr and create a new one as this one's just gotten too messy?

**Comment by ABHAY0O7** [comment]
Hey @Naman-11 
The location of your `info.md` file is wrong.
Please again visit the `CONTRIBUTING.md` and read the task carefully.

> Should i just close this pr and create a new one as this one's just gotten too messy?

You can do which suits you.

**Comment by ABHAY0O7** [comment]
Okay, thanks for your contributions @Naman-11 😄

**Comment by ABHAY0O7** [comment]
Hey @Naman-11 , you didn't follow the PR template, ie instead of 
`Issue : Issue number. #4`
you have to write
`issue: 4`

So, this PR is unpointed. Please make a new PR with proper template.

**Pull request merged**
