### PR TITLE
Go git issue 1 by Ksathwik03

### PR DESCRIPTION
**Pull request by Ksathwik03**
## Title
    Same as Title of the issue you solved. 

## Description - 

    Issue: ISSUENUMBER

    List out all the commands that you used to complete this task from very beginning.

    -
    -
    -

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @Ksathwik03, 
Thanks for opening the PR, but it seems that you didn't follow the PR template, you just copied it.
- image
the above line means that the title of your PR should be same ie `First time contributors.` if you make a PR for issue-1.
- 
image
This line means that you need to mention the issue number for which you made this PR.
- 
image
and this means that you need to specify all the git commands that you used to complete this task.

**Comment by Ksathwik03** [comment]
Sure i will make it according to the rules.

**Comment by ABHAY0O7** [comment]
@Ksathwik03 , don't forget to see the new PR template.

**Comment by Ksathwik03** [comment]
> @Ksathwik03 , don't forget to see the new PR template.

Just before 5 min i opened a pull request bro no worries i will change it

**Pull request closed without merging**
