### PR TITLE
Added info.md

### PR DESCRIPTION
**Pull request by raghavgoel25**
Issue: 4

Commands that I used to complete this issue.

- git clone https://github.com/raghavgoel25/GoGit
- git add .
- git commit -m"Added info.md"
- git push origin main

### CODE REVIEW

**Comment by raghavgoel25** [comment]
> Hey @raghavgoel25
> 
> PR template is not followed.
> 
> Thanks for contributing to OpenCode ✨✨!

Done, please check.

**Comment by ABHAY0O7** [comment]
Hey @rag-hav, please correct the issue number.

**Comment by raghavgoel25** [comment]
> Hey @rag-hav, please correct the issue number.

Done

**Comment by ABHAY0O7** [comment]
Hey @rag-hav , I want you to close this PR and make a new PR. It is very simple, just do it.
Also in that PR, use the same PR template that you used in this PR. 
This one
image

**Pull request closed without merging**
