### PR TITLE
Added Info

### PR DESCRIPTION
**Pull request by saisumanthkumar**
Issue: 4

Commands that I used to complete this issue.
- git clone https://github.com/saisumanthkumar/GoGit.git
- git checkout -b dev
- git add .
- git commit -m "Added Info"
- git push

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
@saisumanthkumar 
Your third command is wrong.

**Comment by saisumanthkumar** [comment]
In third command : by using -am no need to add the files agian

**Comment by saisumanthkumar** [comment]
@ABHAY0O7 edited !!!

**Comment by ABHAY0O7** [comment]
> In third command : by using -am no need to add the files agian

I think it is `-a -m` not `-am`, but if think that you are correct then show me the output of this command (`-am`). 
I will love to be proved wrong. 😄

**Comment by saisumanthkumar** [comment]
@ABHAY0O7 
I followed this tutorial 
https://youtu.be/RGOj5yH7evk
Watch @51:05

**Comment by saisumanthkumar** [comment]
Screenshot (147)

This was the repo link https://github.com/saisumanthkumar/GoGitTestFile

**Comment by ABHAY0O7** [comment]
Okay, in the tutorial it is clearly said that the command is only valid for modified files, not new files.
But `info.md` was a new file so you can't use this command directly. First, you have to tell the git to track that file.
BTW, you wrote all the commands correctly.
So, thanks for your contribution. 👍🏽 
I really learned some new things today. 😄

**Pull request merged**
