### PR TITLE
Push me issue

### PR DESCRIPTION
**Pull request by ashutosh3027**
Issue: 10

Commands that you used to complete this issue.

- git  pull origin main
-  cd .\CONTRIBUTORS\
- mkdir no_name
- git add.
- git commit -m "Push me issue"
-  git push

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @ashutosh3027 
How many times did you use `git add .`?

**Comment by ashutosh3027** [comment]
> Hey @ashutosh3027 How many times did you use `git add .`?

1

**Comment by ashutosh3027** [comment]
1 before test and 1 for editing info.md

**Comment by ashutosh3027** [comment]
means a total 2

**Comment by ABHAY0O7** [comment]
Did you really clone the repo again?

**Comment by ashutosh3027** [comment]
I have clone it early for first issue . In this issue i have just pull

**Comment by ABHAY0O7** [comment]
So, please write the correct commands and remove the unused commands.

**Comment by ashutosh3027** [comment]
So, I have to write all two add commands and pull commands right?

**Comment by ashutosh3027** [comment]
Or just about pull commands

**Comment by ashutosh3027** [comment]
ok thanks

**Comment by ashutosh3027** [comment]
@ABHAY0O7  now?

**Comment by ABHAY0O7** [comment]
join the GoGit VC

**Comment by ABHAY0O7** [comment]
So, finally your answer was 95% correct, but if we talk exact to the point, then the reason is that 
'Git does not track empty directories.
This was the exact reason for that problem, but your was also sufficient.
So kudos to you, you successfully completed this task 🥳 .

**Pull request merged**
