### PR TITLE
I have done all changes.

### PR DESCRIPTION
**Pull request by Ayushi181**
please merge it.

Issue: 4

Commands that you used to complete this issue.

-git clone https://github.com/Ayushi181/GoGit.git
-git add .
-git commit -m"I did the changes in info.md"
-git push origin main

### CODE REVIEW

**Comment by Mitul16** [comment]
@Ayushi181 You have modified the PR template (the first line) and the bot may not be able to detect it.
Please create a new PR after following the instructions from the task #4

Add spaces between the `-` and the _list item_ like so
```
-item1  (WRONG)
- item2 (RIGHT)
```

**Comment by ABHAY0O7** [comment]
@Ayushi181 please do the changes suggested by @Mitul16

**Comment by ABHAY0O7** [comment]
@Ayushi181 
Your commit message is wrong.
Please correct it.

**Comment by Ayushi181** [comment]
How to correct . Please tell

**Comment by ABHAY0O7** [comment]
> How to correct . Please tell.

Actually you used the command
`git commit -m"I have done all changes." -m"please merge it."`
but in the description, you provided us the wrong command.

So clearly you write the commands in the PR description after seeing some old accepted PRs.
This is not acceptable.

Please redo the task in a fair way.
I will advise you to visit the CONTRIBUTING.md and the task again.
I am closing this PR, please make a new one.

**Pull request closed without merging**
