### PR TITLE
done 1st issue

### PR DESCRIPTION
**Pull request by anu-phoenix**
Issue: 4
 
List out all the commands that you used to complete this task from very beginning.

    -git clone https://github.com/opencodeiiita/GoGit.git
    -git add -A
    -git commit -m"done 1st issue"
    -git pull https://github.com/opencodeiiita/GoGit.git
    -git push origin main

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @anu-phoenix 
Please update your PR message with the latest PR template.
Also, visit the GoGit channel of discord.

**Comment by anu-phoenix** [comment]
updated!

**Comment by ABHAY0O7** [comment]
There is an error in the second command. Correct it.

**Comment by anu-phoenix** [comment]
done

**Comment by ABHAY0O7** [comment]
Ok @anu-phoenix, thanks for your contribution.

**Pull request merged**
