### PR TITLE
added myself in contributors

### PR DESCRIPTION
**Pull request by jalanprakhar**
Issue: 4

Commands that you used to complete this issue.
- git clone https://github.com/jalanprakhar/GoGit.git
- cd .\GoGit\
- git add .
- git commit -m "added myself in contributors"
- git push origin main
image

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @jalanprakhar 
Everything is fine except the repo link you provided in your info file.

Please read the task again and update the PR accordingly.

**Comment by jalanprakhar** [comment]
> Hey @jalanprakhar Everything is fine except the repo link you provided in your info file.
> 
> Please read the task again and update the PR accordingly.
is it compulsory to create a new repo?

**Comment by ABHAY0O7** [comment]
> is it compulsory to create a new repo?

Yes, it's not a big deal, you can delete it after merging this PR.

**Comment by ABHAY0O7** [comment]
Thanks for your efforts and PR 😄

**Pull request merged**
