### PR TITLE
Created git-ignore file

### PR DESCRIPTION
**Pull request by kaneki-ken260**
Issue: 87 

The missing git file was .gitignore.
So it was created in the repo.

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
@kaneki-ken260 
Didn't you use any git commands?

**Comment by kaneki-ken260** [comment]
Well Obviously, @ABHAY0O7 

- git clone 
- git status
- git add .
- git commit -m "created git-ignore file"
- git push origin main

**Comment by ABHAY0O7** [comment]
@kaneki-ken260 
Did you really clone the repo again?
I guess not.
Please tell.

**Comment by kaneki-ken260** [comment]
Hey, @ABHAY0O7 

The link provided in my comment redirects to the forked repo which I cloned in my local system.
Why it looks like I have not cloned the repo?

**Comment by ABHAY0O7** [comment]
@kaneki-ken260 
You already cloned the repo during the first task. See this,
image

So there must be a reason to clone this repo again.
Please tell me the reason if you cloned the repo again.
And if not then update your commands.

**Comment by kaneki-ken260** [comment]
@ABHAY0O7 

I didn't fetched and merged the commits in my forked repo
I just forked the updated one again and cloned it again to my local system as I deleted the previously cloned folder in my PC

**Comment by ABHAY0O7** [comment]
@kaneki-ken260 
Don't worry, I was just asking the reason for cloning again, which you explained well.
Don't need to remove the clone command from your message.

**Comment by ABHAY0O7** [comment]
Ok @kaneki-ken260 
Your next half task is this:
Write this line inside file "I".
`*.log`

Now answer this question inside your `info.md`
What this above line that you wrote inside the file "I" will do?

Please complete it before tomorrow 11:59 AM.

**Comment by kaneki-ken260** [comment]
@ABHAY0O7 

Shall I close this pull request and create a new pr????

**Comment by kaneki-ken260** [comment]
@ABHAY0O7 
I have completed the next half of the task

**Comment by ABHAY0O7** [comment]
Nyce work @kaneki-ken260 
You successfully completed this task.

Kudos to you 👏🏽

**Pull request merged**
